service: test-task-serverless-books-api

app: test-task-serverless-books-api
org: lembdev

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    PROVIDER_STAGE: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}'

functions:
  createBook:
    handler: functions/create.handler
    events:
      - http:
          path: books
          method: post
          cors: true
      - http:
          path: book/add
          method: post
          cors: true

  listBooks:
    handler: functions/list.handler
    events:
      - http:
          path: books
          method: get
          cors: true

  getBook:
    handler: functions/get.handler
    events:
      - http:
          path: books/{uuid}
          method: get
          cors: true
      - http:
          path: book/{uuid}
          method: get
          cors: true

  updateBook:
    handler: functions/update.handler
    events:
      - http:
          path: books/{uuid}
          method: put
          cors: true
      - http:
          path: book/{uuid}/update
          method: post
          cors: true

  deleteBook:
    handler: functions/delete.handler
    events:
      - http:
          path: books/{uuid}
          method: delete
          cors: true
      - http:
          path: book/{uuid}/delete
          method: post
          cors: true

resources:
  Resources:
    booksTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
